"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useForm, useFieldArray } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  ArrowLeft,
  Save,
  Plus,
  Trash2,
  Sparkles,
  RefreshCw,
  Layers,
  DollarSign,
  AlertCircle,
  Check,
  Percent,
  Camera,
  Image as ImageIcon,
  CheckCircle2,
  Package,
} from "lucide-react";
import { toast } from "sonner";

import {
  productFormSchema,
  generateEan13,
  isValidEan13,
  type ProductFormData,
  type ProductVariantFormData,
} from "@/schemas/product";
import { productService } from "@/services/product";
import type { Category, Product } from "@/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

interface ProductFormProps {
  initialData?: Product | null;
  categories: Category[];
  isEditing?: boolean;
}

const AVAILABLE_SIZES = ["PP", "P", "M", "G", "GG", "XG", "G1", "G2", "34", "36", "38", "40", "42", "44", "46", "48"];

/**
 * Utilitário para redimensionar e comprimir fotos de produtos
 */
async function compressImageFile(file: File, maxDim = 1024, quality = 0.85): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (event) => {
      const img = new window.Image();
      img.onload = () => {
        let width = img.width;
        let height = img.height;

        if (width > maxDim || height > maxDim) {
          if (width > height) {
            height = Math.round((height * maxDim) / width);
            width = maxDim;
          } else {
            width = Math.round((width * maxDim) / height);
            height = maxDim;
          }
        }

        const canvas = document.createElement("canvas");
        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext("2d");
        if (!ctx) {
          resolve(event.target?.result as string);
          return;
        }

        ctx.drawImage(img, 0, 0, width, height);
        const compressedDataUrl = canvas.toDataURL("image/jpeg", quality);
        resolve(compressedDataUrl);
      };
      img.onerror = () => reject(new Error("Falha ao carregar a imagem."));
      img.src = event.target?.result as string;
    };
    reader.onerror = () => reject(new Error("Falha ao ler o arquivo."));
    reader.readAsDataURL(file);
  });
}

export function ProductForm({
  initialData,
  categories,
  isEditing = false,
}: ProductFormProps) {
  const router = useRouter();

  // Código EAN-13 gerado automaticamente para produto novo
  const [autoGeneratedEan] = React.useState(() => generateEan13("789"));
  const initialEan = initialData?.ean13 || initialData?.sku || autoGeneratedEan;

  // Estado para alternar entre Tamanho Único e Variações de Tamanho
  const [isMultiSizeActive, setIsMultiSizeActive] = React.useState<boolean>(() => {
    if (initialData?.variants && initialData.variants.length > 1) {
      return initialData.variants.some((v) => v.size !== "Único");
    }
    return false;
  });

  const [selectedSizes, setSelectedSizes] = React.useState<string[]>(["P", "M", "G", "GG"]);

  // Estados da Foto & Câmera
  const [isPhotoModalOpen, setIsPhotoModalOpen] = React.useState(false);
  const [isCameraOpen, setIsCameraOpen] = React.useState(false);
  const [cameraFacing, setCameraFacing] = React.useState<"environment" | "user">("environment");
  const videoRef = React.useRef<HTMLVideoElement>(null);
  const streamRef = React.useRef<MediaStream | null>(null);

  // Referências para inputs de arquivo
  const fileInputRef = React.useRef<HTMLInputElement>(null);
  const nativeCameraInputRef = React.useRef<HTMLInputElement>(null);

  const defaultValues: ProductFormData = {
    name: initialData?.name || "",
    ean13: initialEan,
    sku: initialEan,
    image_url: initialData?.image_url || null,
    category_id: initialData?.category_id || (categories[0]?.id ?? ""),
    cost_price: initialData?.cost_price || 0,
    sale_price: initialData?.sale_price || 0,
    description: initialData?.description || "",
    initial_stock: 0,
    active: initialData?.active ?? true,
    variants: initialData?.variants && initialData.variants.length > 0
      ? initialData.variants.map((v) => {
          const vEan = v.ean13 || v.barcode || v.sku_variant || generateEan13("789");
          return {
            id: v.id,
            size: v.size || "Único",
            color: "Padrão",
            ean13: vEan,
            sku_variant: vEan,
            barcode: vEan,
            stock_quantity: 0,
            active: v.active,
          };
        })
      : [
          {
            size: "Único",
            color: "Padrão",
            ean13: initialEan,
            sku_variant: initialEan,
            barcode: initialEan,
            stock_quantity: 0,
            active: true,
          },
        ],
  };

  const {
    register,
    control,
    handleSubmit,
    watch,
    setValue,
    formState: { errors, isSubmitting },
  } = useForm<ProductFormData>({
    resolver: zodResolver(productFormSchema),
    defaultValues,
  });

  const { fields, append, remove, replace } = useFieldArray({
    control,
    name: "variants",
  });

  const currentEan = watch("ean13") || "";
  const currentImageUrl = watch("image_url");
  const costPrice = watch("cost_price") || 0;
  const salePrice = watch("sale_price") || 0;
  const watchedVariants = watch("variants");

  // Total de estoque somado nas variações
  const totalStockCount = React.useMemo(() => {
    return (watchedVariants || []).reduce((acc, v) => acc + Number(v?.stock_quantity || 0), 0);
  }, [watchedVariants]);

  // Margem de Lucro Bruta Estimada
  const profitMargin =
    salePrice > 0 && costPrice >= 0
      ? (((salePrice - costPrice) / salePrice) * 100).toFixed(1)
      : null;

  // Alternar entre Tamanho Único e Variações
  const toggleMultiSize = () => {
    const nextState = !isMultiSizeActive;
    setIsMultiSizeActive(nextState);

    if (!nextState) {
      // Reverter para Tamanho Único
      const firstEan = watch("variants.0.ean13") || initialEan;
      const currentStock = watch("variants.0.stock_quantity") || 0;
      replace([
        {
          size: "Único",
          color: "Padrão",
          ean13: firstEan,
          sku_variant: firstEan,
          barcode: firstEan,
          stock_quantity: currentStock,
          active: true,
        },
      ]);
      toast.info("Modo Tamanho Único ativado.");
    } else {
      // Ativar variações do P ao XG
      generateSizesMatrix(["P", "M", "G", "GG", "XG"]);
      toast.info("Variações de tamanho ativadas (P ao XG).");
    }
  };

  // Alternar tamanho individual no gerador
  const toggleSize = (size: string) => {
    setSelectedSizes((prev) =>
      prev.includes(size) ? prev.filter((s) => s !== size) : [...prev, size]
    );
  };

  // Gerar matriz de tamanhos
  const generateSizesMatrix = (sizesToUse?: string[]) => {
    const targetSizes = sizesToUse || selectedSizes;
    if (targetSizes.length === 0) {
      toast.warning("Selecione pelo menos um tamanho.");
      return;
    }

    const currentBaseStock = watch("variants.0.stock_quantity") || 0;
    const newVariants: ProductVariantFormData[] = targetSizes.map((size) => {
      const variantEan = generateEan13("789");
      return {
        size,
        color: "Padrão",
        ean13: variantEan,
        sku_variant: variantEan,
        barcode: variantEan,
        stock_quantity: currentBaseStock > 0 ? currentBaseStock : 0,
        active: true,
      };
    });

    replace(newVariants);
    toast.success(`${newVariants.length} variações geradas com códigos EAN-13 individuais!`);
  };

  // Gerar novo código EAN-13 para o modelo base
  const handleGenerateNewEan = () => {
    const newEan = generateEan13("789");
    setValue("ean13", newEan, { shouldValidate: true, shouldDirty: true });
    setValue("sku", newEan);
    if (!isMultiSizeActive && fields.length > 0) {
      setValue("variants.0.ean13", newEan);
      setValue("variants.0.sku_variant", newEan);
      setValue("variants.0.barcode", newEan);
    }
    toast.info(`Novo código EAN-13 gerado: ${newEan}`);
  };

  // Gerar novo código EAN-13 para uma variação específica
  const handleRegenerateVariantEan = (index: number) => {
    const newEan = generateEan13("789");
    setValue(`variants.${index}.ean13`, newEan, { shouldValidate: true, shouldDirty: true });
    setValue(`variants.${index}.sku_variant`, newEan);
    setValue(`variants.${index}.barcode`, newEan);
    toast.info(`EAN-13 atualizado na variação: ${newEan}`);
  };

  // Iniciar fluxo da Câmera ao vivo
  const startCamera = async (facing: "environment" | "user" = cameraFacing) => {
    try {
      if (streamRef.current) {
        streamRef.current.getTracks().forEach((track) => track.stop());
      }
      setIsCameraOpen(true);
      const stream = await navigator.mediaDevices.getUserMedia({
        video: {
          facingMode: facing,
          width: { ideal: 1280 },
          height: { ideal: 1280 },
        },
      });
      streamRef.current = stream;
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
      }
    } catch {
      setIsCameraOpen(false);
      if (nativeCameraInputRef.current) {
        nativeCameraInputRef.current.click();
      } else {
        toast.error("Câmera indisponível. Utilize o botão 'Escolher Arquivo'.");
      }
    }
  };

  // Parar Câmera
  const stopCamera = React.useCallback(() => {
    if (streamRef.current) {
      streamRef.current.getTracks().forEach((track) => track.stop());
      streamRef.current = null;
    }
    setIsCameraOpen(false);
  }, []);

  // Fechar Modal de Foto
  const closePhotoModal = () => {
    stopCamera();
    setIsPhotoModalOpen(false);
  };

  // Alternar câmera frontal/traseira
  const toggleCameraFacing = async () => {
    const nextFacing = cameraFacing === "environment" ? "user" : "environment";
    setCameraFacing(nextFacing);
    await startCamera(nextFacing);
  };

  // Capturar foto
  const capturePhoto = () => {
    if (!videoRef.current) return;
    const video = videoRef.current;
    const canvas = document.createElement("canvas");
    canvas.width = video.videoWidth || 800;
    canvas.height = video.videoHeight || 800;
    const ctx = canvas.getContext("2d");
    if (ctx) {
      ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
      const dataUrl = canvas.toDataURL("image/jpeg", 0.85);
      setValue("image_url", dataUrl, { shouldDirty: true });
      toast.success("Foto do produto capturada com sucesso!");
    }
    stopCamera();
    setIsPhotoModalOpen(false);
  };

  // Upload de arquivo
  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    try {
      const compressed = await compressImageFile(file);
      setValue("image_url", compressed, { shouldDirty: true });
      setIsPhotoModalOpen(false);
      toast.success("Foto carregada com sucesso!");
    } catch {
      toast.error("Erro ao carregar a foto do produto.");
    } finally {
      e.target.value = "";
    }
  };

  // Remover foto
  const handleRemovePhoto = () => {
    setValue("image_url", null, { shouldDirty: true });
    toast.info("Foto removida.");
  };

  React.useEffect(() => {
    return () => {
      if (streamRef.current) {
        streamRef.current.getTracks().forEach((track) => track.stop());
      }
    };
  }, []);

  const onSubmit = async (data: ProductFormData) => {
    try {
      const ean = data.ean13 || generateEan13("789");
      const submissionData: ProductFormData = {
        ...data,
        ean13: ean,
        sku: ean,
        image_url: data.image_url || null,
        variants: data.variants.map((v) => {
          const vEan = v.ean13 || generateEan13("789");
          return {
            ...v,
            color: "Padrão",
            ean13: vEan,
            sku_variant: vEan,
            barcode: vEan,
            stock_quantity: Number(v.stock_quantity || 0),
          };
        }),
      };

      if (isEditing && initialData?.id) {
        const res = await productService.updateProduct(initialData.id, submissionData);
        if (res.error) {
          toast.error(res.error);
          return;
        }
        toast.success("Produto atualizado com sucesso!");
      } else {
        const res = await productService.createProduct(submissionData);
        if (res.error) {
          toast.error(res.error);
          return;
        }
        toast.success("Produto cadastrado com sucesso!");
      }

      router.push("/products");
      router.refresh();
    } catch {
      toast.error("Ocorreu um erro ao salvar o produto.");
    }
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-8 animate-in fade-in duration-300">
      {/* Botões de Ação Superiores */}
      <div className="flex items-center justify-between pb-4 border-b">
        <Link href="/products">
          <Button variant="ghost" size="sm" className="gap-2">
            <ArrowLeft className="h-4 w-4" />
            Voltar para Produtos
          </Button>
        </Link>
        <div className="flex items-center gap-3">
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={() => router.push("/products")}
            disabled={isSubmitting}
          >
            Cancelar
          </Button>
          <Button
            type="submit"
            size="sm"
            disabled={isSubmitting}
            className="gap-2 bg-gradient-to-r from-[#E06B67] to-[#F48884] hover:opacity-95 text-white shadow-xs"
          >
            <Save className="h-4 w-4" />
            {isSubmitting ? "Salvando..." : isEditing ? "Salvar Alterações" : "Salvar Produto"}
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Coluna 1 & 2: Dados Básicos e Precificação */}
        <div className="lg:col-span-2 space-y-6">
          {/* Card: Identificação */}
          <Card className="shadow-sm border">
            <CardHeader>
              <CardTitle className="text-base">Identificação da Peça</CardTitle>
              <CardDescription>
                Informe o nome do produto (se tiver cor específica, coloque aqui no nome) e o código EAN-13.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="sm:col-span-2 space-y-2">
                  <Label htmlFor="name">Nome da Peça *</Label>
                  <Input
                    id="name"
                    placeholder="Ex: Vestido Midi Floral Rosa, Carteira Couro Preto..."
                    disabled={isSubmitting}
                    {...register("name")}
                  />
                  {errors.name && (
                    <p className="text-xs text-destructive">{errors.name.message}</p>
                  )}
                </div>

                <div className="space-y-2">
                  <Label htmlFor="ean13" className="flex items-center gap-1.5">
                    <span>Código EAN-13 *</span>
                  </Label>
                  <div className="relative flex items-center">
                    <Input
                      id="ean13"
                      maxLength={13}
                      placeholder="Ex: 7891234567890"
                      className="font-mono font-semibold text-foreground pr-24 tracking-wider"
                      disabled={isSubmitting}
                      {...register("ean13")}
                    />
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      onClick={handleGenerateNewEan}
                      disabled={isSubmitting}
                      className="absolute right-1 top-1/2 -translate-y-1/2 h-7 text-xs text-[#E06B67] hover:text-[#E06B67] hover:bg-pink-50 px-2 gap-1 rounded font-medium transition-colors"
                      title="Gerar código EAN-13 automático com dígito verificador"
                    >
                      <RefreshCw className="w-3 h-3" />
                      Gerar EAN
                    </Button>
                  </div>
                  <div className="flex items-center justify-between text-[11px] text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <Check className="w-3 h-3 text-emerald-600" />
                      Oficial (13 dígitos)
                    </span>
                    {currentEan && isValidEan13(currentEan) && (
                      <span className="text-[10px] text-emerald-600 font-medium flex items-center gap-1">
                        <CheckCircle2 className="w-3 h-3" />
                        Válido
                      </span>
                    )}
                  </div>
                  {errors.ean13 && (
                    <p className="text-xs text-destructive">{errors.ean13.message}</p>
                  )}
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="category_id">Categoria</Label>
                  <select
                    id="category_id"
                    disabled={isSubmitting}
                    className="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                    {...register("category_id")}
                  >
                    <option value="" className="bg-background text-foreground">
                      Selecione uma categoria
                    </option>
                    {categories.map((c) => (
                      <option key={c.id} value={c.id} className="bg-background text-foreground">
                        {c.name}
                      </option>
                    ))}
                  </select>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="active">Status</Label>
                  <select
                    id="active"
                    disabled={isSubmitting}
                    className="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                    value={watch("active") ? "true" : "false"}
                    onChange={(e) => setValue("active", e.target.value === "true")}
                  >
                    <option value="true" className="bg-background text-foreground">
                      Ativo (Disponível para venda no PDV)
                    </option>
                    <option value="false" className="bg-background text-foreground">
                      Inativo (Oculto)
                    </option>
                  </select>
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="description">Descrição / Detalhes</Label>
                <textarea
                  id="description"
                  rows={3}
                  placeholder="Ex: Modelo de alta durabilidade, acabamento refinado..."
                  disabled={isSubmitting}
                  className="flex w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                  {...register("description")}
                />
              </div>
            </CardContent>
          </Card>

          {/* Card: Precificação & Quantidade em Estoque */}
          <Card className="shadow-sm border">
            <CardHeader>
              <div className="flex items-center gap-2">
                <DollarSign className="h-4 w-4 text-[#E06B67]" />
                <CardTitle className="text-base">Preços & Quantidade de Estoque</CardTitle>
              </div>
              <CardDescription>
                Valores de custo, venda e quantidade física que você está adicionando.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 items-center">
                <div className="space-y-2">
                  <Label htmlFor="cost_price">Preço de Custo (R$)</Label>
                  <Input
                    id="cost_price"
                    type="number"
                    step="0.01"
                    min="0"
                    placeholder="0,00"
                    disabled={isSubmitting}
                    {...register("cost_price")}
                  />
                  {errors.cost_price && (
                    <p className="text-xs text-destructive">{errors.cost_price.message}</p>
                  )}
                </div>

                <div className="space-y-2">
                  <Label htmlFor="sale_price">Preço de Venda (R$) *</Label>
                  <Input
                    id="sale_price"
                    type="number"
                    step="0.01"
                    min="0.01"
                    placeholder="0,00"
                    disabled={isSubmitting}
                    {...register("sale_price")}
                  />
                  {errors.sale_price && (
                    <p className="text-xs text-destructive">{errors.sale_price.message}</p>
                  )}
                </div>

                {/* Margem Bruta */}
                <div className="rounded-lg border bg-muted/40 p-3 flex flex-col justify-center">
                  <span className="text-xs text-muted-foreground flex items-center gap-1">
                    <Percent className="h-3 w-3" />
                    Margem Estimada
                  </span>
                  <span
                    className={`text-lg font-bold mt-0.5 ${
                      Number(profitMargin) > 40
                        ? "text-emerald-600 dark:text-emerald-400"
                        : Number(profitMargin) > 20
                        ? "text-blue-600 dark:text-blue-400"
                        : "text-amber-600 dark:text-amber-400"
                    }`}
                  >
                    {profitMargin !== null ? `${profitMargin}%` : "-"}
                  </span>
                </div>
              </div>

              {/* Quantidade Rápida se for Tamanho Único */}
              {!isMultiSizeActive && fields.length === 1 && (
                <div className="mt-4 pt-4 border-t flex items-center justify-between bg-muted/20 p-3 rounded-lg border">
                  <div>
                    <Label htmlFor="single_stock" className="text-xs font-bold text-foreground flex items-center gap-1.5">
                      <Package className="w-4 h-4 text-[#E06B67]" />
                      Quantidade em Estoque Adicionada
                    </Label>
                    <p className="text-[11px] text-muted-foreground">
                      Quantas unidades desta peça você possui para dar entrada no estoque.
                    </p>
                  </div>
                  <div className="w-32">
                    <Input
                      id="single_stock"
                      type="number"
                      min="0"
                      placeholder="0"
                      className="h-10 text-base font-bold text-center"
                      disabled={isSubmitting}
                      {...register("variants.0.stock_quantity" as any)}
                    />
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Coluna 3: Gerador de Tamanhos e Foto */}
        <div className="space-y-6">
          {/* Card: Gerador de Tamanhos (Aparece quando Variações estão Ativas) */}
          {isMultiSizeActive && (
            <Card className="shadow-sm border bg-muted/20 animate-in fade-in duration-200">
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Sparkles className="h-4 w-4 text-[#E06B67]" />
                    <CardTitle className="text-sm font-semibold">Tamanhos (P ao XG)</CardTitle>
                  </div>
                  <Badge variant="outline" className="text-[10px] text-[#E06B67] border-[#E06B67]/30">
                    Variações Ativas
                  </Badge>
                </div>
                <CardDescription className="text-xs">
                  Selecione os tamanhos para gerar os códigos EAN-13 individuais.
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                {/* Botões Rápidos de Grade */}
                <div className="flex gap-2">
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    className="text-xs h-7 flex-1"
                    onClick={() => {
                      setSelectedSizes(["P", "M", "G", "GG"]);
                      generateSizesMatrix(["P", "M", "G", "GG"]);
                    }}
                  >
                    Grade P ao GG
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    className="text-xs h-7 flex-1 font-semibold text-[#E06B67] border-[#E06B67]/40 hover:bg-[#E06B67]/10"
                    onClick={() => {
                      setSelectedSizes(["P", "M", "G", "GG", "XG"]);
                      generateSizesMatrix(["P", "M", "G", "GG", "XG"]);
                    }}
                  >
                    Grade P ao XG
                  </Button>
                </div>

                {/* Seleção de Tamanhos Individuais */}
                <div className="space-y-1.5">
                  <Label className="text-xs font-semibold">Tamanhos Disponíveis</Label>
                  <div className="flex flex-wrap gap-1.5">
                    {AVAILABLE_SIZES.map((size) => {
                      const isSelected = selectedSizes.includes(size);
                      return (
                        <button
                          type="button"
                          key={size}
                          onClick={() => toggleSize(size)}
                          className={`px-2.5 py-1 text-xs font-medium rounded-md border transition-all ${
                            isSelected
                              ? "bg-[#E06B67] text-white border-[#E06B67]"
                              : "bg-background text-foreground border-input hover:border-[#E06B67]/50"
                          }`}
                        >
                          {size}
                        </button>
                      );
                    })}
                  </div>
                </div>

                <Button
                  type="button"
                  variant="secondary"
                  className="w-full gap-2 text-xs h-9 font-medium"
                  onClick={() => generateSizesMatrix()}
                >
                  <Sparkles className="h-3.5 w-3.5 text-[#E06B67]" />
                  Aplicar {selectedSizes.length} Tamanhos na Grade
                </Button>
              </CardContent>
            </Card>
          )}

          {/* Card: Foto do Produto */}
          <Card className="shadow-sm border">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <ImageIcon className="h-4 w-4 text-[#E06B67]" />
                  <CardTitle className="text-sm font-semibold">Foto do Produto</CardTitle>
                </div>
                <Badge variant="outline" className="text-[10px] text-muted-foreground">
                  Catálogo & PDV
                </Badge>
              </div>
              <CardDescription className="text-xs">
                Foto da peça para identificação visual nas vendas e catálogo.
              </CardDescription>
            </CardHeader>
            <CardContent>
              {currentImageUrl ? (
                <div className="space-y-3">
                  <div className="relative w-full aspect-4/3 rounded-xl border border-border overflow-hidden bg-muted/30 group shadow-xs">
                    <img
                      src={currentImageUrl}
                      alt="Foto do Produto"
                      className="w-full h-full object-cover"
                    />
                    <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-2">
                      <Button
                        type="button"
                        size="sm"
                        variant="secondary"
                        onClick={() => setIsPhotoModalOpen(true)}
                        className="gap-1.5 text-xs font-medium shadow-md"
                      >
                        <Camera className="w-3.5 h-3.5 text-[#E06B67]" />
                        Trocar Foto
                      </Button>
                      <Button
                        type="button"
                        size="sm"
                        variant="destructive"
                        onClick={handleRemovePhoto}
                        className="gap-1.5 text-xs shadow-md"
                        title="Remover foto"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </Button>
                    </div>
                  </div>

                  <div className="flex gap-2">
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      onClick={() => setIsPhotoModalOpen(true)}
                      className="w-full gap-2 text-xs border-[#E06B67]/30 hover:border-[#E06B67] hover:bg-[#E06B67]/5 text-foreground"
                    >
                      <Camera className="w-3.5 h-3.5 text-[#E06B67]" />
                      Alterar Foto
                    </Button>
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      onClick={handleRemovePhoto}
                      className="text-xs text-rose-600 hover:text-rose-700 hover:bg-rose-50 px-2.5"
                      title="Remover foto"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </Button>
                  </div>
                </div>
              ) : (
                <div
                  onClick={() => setIsPhotoModalOpen(true)}
                  className="border-2 border-dashed border-border/80 hover:border-[#E06B67]/60 rounded-xl p-5 flex flex-col items-center justify-center text-center cursor-pointer transition-all hover:bg-[#E06B67]/5 group"
                >
                  <div className="h-11 w-11 rounded-xl bg-[#E06B67]/10 group-hover:bg-[#E06B67]/20 flex items-center justify-center text-[#E06B67] mb-2.5 transition-colors">
                    <Camera className="w-5 h-5" />
                  </div>
                  <p className="text-xs font-semibold text-foreground">Nenhuma foto adicionada</p>
                  <p className="text-[11px] text-muted-foreground mt-0.5">
                    Tire uma foto ou selecione do computador/celular
                  </p>
                  <Button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      setIsPhotoModalOpen(true);
                    }}
                    className="mt-3.5 gap-2 text-xs bg-gradient-to-r from-[#E06B67] to-[#F48884] hover:opacity-95 text-white shadow-xs w-full"
                  >
                    <Camera className="w-3.5 h-3.5" />
                    Escolher ou Tirar Foto
                  </Button>
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Seção: Variações de Grade & Códigos EAN-13 */}
      <Card className="shadow-sm border">
        <CardHeader className="flex flex-col sm:flex-row sm:items-center justify-between pb-3 gap-3">
          <div>
            <div className="flex items-center gap-2">
              <Layers className="h-4 w-4 text-[#E06B67]" />
              <CardTitle className="text-base">Variações de Grade & Códigos EAN-13</CardTitle>
            </div>
            <CardDescription className="text-xs mt-1">
              {isMultiSizeActive
                ? "Grade ativa com múltiplos tamanhos (P ao XG). Digite a quantidade em estoque para cada um."
                : "Produto configurado como Tamanho Único. Se possuir tamanhos variados (P ao XG), clique no botão ao lado."}
            </CardDescription>
          </div>

          <div className="flex items-center gap-2">
            <Button
              type="button"
              variant={isMultiSizeActive ? "secondary" : "outline"}
              size="sm"
              onClick={toggleMultiSize}
              className={`gap-1.5 text-xs font-semibold transition-all ${
                isMultiSizeActive
                  ? "bg-[#E06B67] hover:bg-[#E06B67]/90 text-white shadow-xs"
                  : "border-[#E06B67] text-[#E06B67] hover:bg-[#E06B67]/10"
              }`}
            >
              <Sparkles className="h-3.5 w-3.5" />
              {isMultiSizeActive ? "✓ Variações de Tamanho Ativas" : "Ativar Variações de Tamanho"}
            </Button>

            {isMultiSizeActive && (
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => {
                  append({
                    size: "M",
                    color: "Padrão",
                    ean13: generateEan13("789"),
                    sku_variant: "",
                    barcode: "",
                    stock_quantity: 0,
                    active: true,
                  });
                }}
                className="gap-1.5 text-xs"
              >
                <Plus className="h-3.5 w-3.5 text-[#E06B67]" />
                + Tamanho
              </Button>
            )}
          </div>
        </CardHeader>
        <CardContent>
          {errors.variants && (
            <div className="mb-4 flex items-center gap-2 rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-xs text-destructive">
              <AlertCircle className="h-4 w-4 shrink-0" />
              <p>{errors.variants.message}</p>
            </div>
          )}

          <div className="overflow-x-auto border rounded-lg">
            <table className="w-full text-left text-xs">
              <thead className="bg-muted/50 border-b font-semibold text-muted-foreground">
                <tr>
                  <th className="px-3 py-2 w-32">Tamanho *</th>
                  <th className="px-3 py-2 text-center w-36">Quantidade Estoque</th>
                  <th className="px-3 py-2">Código EAN-13 da Peça (13 dígitos) *</th>
                  <th className="px-3 py-2 text-center w-20">Ativo</th>
                  {isMultiSizeActive && fields.length > 1 && (
                    <th className="px-3 py-2 text-right w-16">Remover</th>
                  )}
                </tr>
              </thead>
              <tbody className="divide-y">
                {fields.length === 0 ? (
                  <tr>
                    <td colSpan={5} className="px-4 py-8 text-center text-muted-foreground">
                      Nenhuma variação adicionada.
                    </td>
                  </tr>
                ) : (
                  fields.map((field, index) => (
                    <tr key={field.id} className="hover:bg-muted/20">
                      {/* Tamanho */}
                      <td className="p-2">
                        <Input
                          placeholder="Tam (Único, P...)"
                          className="h-8 text-xs font-semibold"
                          disabled={isSubmitting}
                          {...register(`variants.${index}.size`)}
                        />
                      </td>

                      {/* Quantidade em Estoque */}
                      <td className="p-2 text-center">
                        <Input
                          type="number"
                          min="0"
                          placeholder="0"
                          className="h-8 text-xs text-center font-bold"
                          disabled={isSubmitting}
                          {...register(`variants.${index}.stock_quantity` as any)}
                        />
                      </td>

                      {/* Código EAN-13 */}
                      <td className="p-2">
                        <div className="relative flex items-center">
                          <Input
                            placeholder="789..."
                            maxLength={13}
                            className="h-8 text-xs font-mono font-medium pr-16"
                            disabled={isSubmitting}
                            {...register(`variants.${index}.ean13`)}
                          />
                          <Button
                            type="button"
                            variant="ghost"
                            size="sm"
                            onClick={() => handleRegenerateVariantEan(index)}
                            disabled={isSubmitting}
                            className="absolute right-1 top-1/2 -translate-y-1/2 h-6 px-1.5 text-[10px] text-[#E06B67] hover:bg-pink-50"
                            title="Gerar novo código EAN-13 para esta variação"
                          >
                            <RefreshCw className="w-2.5 h-2.5 mr-1" />
                            Gerar
                          </Button>
                        </div>
                      </td>

                      {/* Ativo */}
                      <td className="p-2 text-center">
                        <input
                          type="checkbox"
                          className="h-4 w-4 rounded border-input text-primary focus:ring-primary cursor-pointer"
                          disabled={isSubmitting}
                          {...register(`variants.${index}.active`)}
                        />
                      </td>

                      {/* Remover */}
                      {isMultiSizeActive && fields.length > 1 && (
                        <td className="p-2 text-right">
                          <Button
                            type="button"
                            variant="ghost"
                            size="icon"
                            onClick={() => remove(index)}
                            className="h-7 w-7 text-muted-foreground hover:text-destructive"
                            title="Remover variação"
                          >
                            <Trash2 className="h-3.5 w-3.5" />
                          </Button>
                        </td>
                      )}
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </CardContent>
        <CardFooter className="flex justify-between items-center border-t py-4 text-xs text-muted-foreground">
          <div className="flex items-center gap-4">
            <span>Tamanhos: {fields.length}</span>
            <span className="font-semibold text-foreground">
              Total de Peças em Estoque: {totalStockCount} un
            </span>
          </div>
          <Button
            type="submit"
            disabled={isSubmitting}
            className="gap-2 bg-gradient-to-r from-[#E06B67] to-[#F48884] hover:opacity-95 text-white shadow-xs"
          >
            <Save className="h-4 w-4" />
            {isSubmitting ? "Salvando..." : isEditing ? "Salvar Alterações" : "Salvar Produto"}
          </Button>
        </CardFooter>
      </Card>

      {/* MODAL: ESCOLHER OU TIRAR FOTO */}
      {isPhotoModalOpen && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-background rounded-2xl max-w-md w-full p-6 shadow-2xl border space-y-4 animate-in fade-in zoom-in-95 duration-150">
            <div className="flex items-center justify-between border-b pb-3">
              <div className="flex items-center gap-2.5">
                <div className="w-8 h-8 rounded-lg bg-[#E06B67]/10 text-[#E06B67] flex items-center justify-center">
                  <Camera className="w-4 h-4" />
                </div>
                <div>
                  <h3 className="font-bold text-foreground text-sm">Foto da Peça</h3>
                  <p className="text-[11px] text-muted-foreground">Tire com a câmera ou escolha um arquivo</p>
                </div>
              </div>
              <Button variant="ghost" size="icon" className="h-7 w-7" onClick={closePhotoModal}>
                <span className="sr-only">Fechar</span>
                &times;
              </Button>
            </div>

            {/* Visualização de Câmera ao vivo */}
            {isCameraOpen ? (
              <div className="space-y-3">
                <div className="relative aspect-square w-full rounded-xl overflow-hidden bg-black border">
                  <video
                    ref={videoRef}
                    autoPlay
                    playsInline
                    muted
                    className="w-full h-full object-cover"
                  />
                  <Button
                    type="button"
                    size="icon"
                    variant="secondary"
                    onClick={toggleCameraFacing}
                    className="absolute top-2 right-2 h-8 w-8 rounded-full bg-black/50 text-white hover:bg-black/70"
                    title="Alternar câmera frontal/traseira"
                  >
                    <RefreshCw className="w-4 h-4" />
                  </Button>
                </div>

                <div className="flex gap-2">
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={stopCamera}
                    className="flex-1 text-xs"
                  >
                    Cancelar
                  </Button>
                  <Button
                    type="button"
                    size="sm"
                    onClick={capturePhoto}
                    className="flex-1 text-xs bg-gradient-to-r from-[#E06B67] to-[#F48884] text-white font-bold"
                  >
                    Capturar Foto
                  </Button>
                </div>
              </div>
            ) : (
              <div className="space-y-3 pt-2">
                <button
                  type="button"
                  onClick={() => startCamera()}
                  className="w-full p-4 rounded-xl border border-border/80 hover:border-[#E06B67] hover:bg-[#E06B67]/5 flex items-center gap-3 transition-all text-left group"
                >
                  <div className="w-10 h-10 rounded-xl bg-[#E06B67]/10 group-hover:bg-[#E06B67]/20 text-[#E06B67] flex items-center justify-center shrink-0 transition-colors">
                    <Camera className="w-5 h-5" />
                  </div>
                  <div>
                    <h4 className="text-xs font-semibold text-foreground">Abrir Câmera</h4>
                    <p className="text-[11px] text-muted-foreground mt-0.5">
                      Tirar foto ao vivo usando a câmera do aparelho
                    </p>
                  </div>
                </button>

                <button
                  type="button"
                  onClick={() => fileInputRef.current?.click()}
                  className="w-full p-4 rounded-xl border border-border/80 hover:border-[#E06B67] hover:bg-[#E06B67]/5 flex items-center gap-3 transition-all text-left group"
                >
                  <div className="w-10 h-10 rounded-xl bg-[#E06B67]/10 group-hover:bg-[#E06B67]/20 text-[#E06B67] flex items-center justify-center shrink-0 transition-colors">
                    <ImageIcon className="w-5 h-5" />
                  </div>
                  <div>
                    <h4 className="text-xs font-semibold text-foreground">Escolher Arquivo</h4>
                    <p className="text-[11px] text-muted-foreground mt-0.5">
                      Selecionar foto salva do computador ou galeria
                    </p>
                  </div>
                </button>

                <input
                  type="file"
                  ref={fileInputRef}
                  accept="image/*"
                  onChange={handleFileChange}
                  className="hidden"
                />

                <input
                  type="file"
                  ref={nativeCameraInputRef}
                  accept="image/*"
                  capture="environment"
                  onChange={handleFileChange}
                  className="hidden"
                />
              </div>
            )}
          </div>
        </div>
      )}
    </form>
  );
}
