"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useForm, useFieldArray } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  ArrowLeft,
  Save,
  Plus,
  Trash2,
  Sparkles,
  RefreshCw,
  Layers,
  Shirt,
  DollarSign,
  AlertCircle,
  Check,
  Percent,
  Camera,
  Upload,
  Image as ImageIcon,
  X,
  RotateCcw,
  Barcode,
  CheckCircle2,
} from "lucide-react";
import { toast } from "sonner";

import {
  productFormSchema,
  generateEan13,
  isValidEan13,
  type ProductFormData,
  type ProductVariantFormData,
} from "@/schemas/product";
import { productService } from "@/services/product";
import type { Category, Product } from "@/types";
import {
  COMMON_CLOTHING_SIZES,
  COMMON_CLOTHING_COLORS,
} from "@/types/product";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

interface ProductFormProps {
  initialData?: Product | null;
  categories: Category[];
  isEditing?: boolean;
}

/**
 * Utilitário para redimensionar e comprimir fotos de produtos
 * Mantém peso leve (< 200KB) e qualidade nítida para catálogo e PDV
 */
async function compressImageFile(file: File, maxDim = 1024, quality = 0.85): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (event) => {
      const img = new window.Image();
      img.onload = () => {
        let width = img.width;
        let height = img.height;

        if (width > maxDim || height > maxDim) {
          if (width > height) {
            height = Math.round((height * maxDim) / width);
            width = maxDim;
          } else {
            width = Math.round((width * maxDim) / height);
            height = maxDim;
          }
        }

        const canvas = document.createElement("canvas");
        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext("2d");
        if (!ctx) {
          resolve(event.target?.result as string);
          return;
        }

        ctx.drawImage(img, 0, 0, width, height);
        const compressedDataUrl = canvas.toDataURL("image/jpeg", quality);
        resolve(compressedDataUrl);
      };
      img.onerror = () => reject(new Error("Falha ao carregar a imagem."));
      img.src = event.target?.result as string;
    };
    reader.onerror = () => reject(new Error("Falha ao ler o arquivo."));
    reader.readAsDataURL(file);
  });
}

export function ProductForm({
  initialData,
  categories,
  isEditing = false,
}: ProductFormProps) {
  const router = useRouter();

  // Estados locais para o gerador de grade rápida
  const [selectedSizes, setSelectedSizes] = React.useState<string[]>([]);
  const [selectedColors, setSelectedColors] = React.useState<string[]>([]);
  const [customColor, setCustomColor] = React.useState("");

  // Estados da Câmera ao vivo
  const [isCameraOpen, setIsCameraOpen] = React.useState(false);
  const [cameraFacing, setCameraFacing] = React.useState<"environment" | "user">("environment");
  const videoRef = React.useRef<HTMLVideoElement>(null);
  const streamRef = React.useRef<MediaStream | null>(null);

  // Referências para inputs de arquivo
  const fileInputRef = React.useRef<HTMLInputElement>(null);
  const nativeCameraInputRef = React.useRef<HTMLInputElement>(null);

  // Código EAN-13 gerado automaticamente para produto novo
  const [autoGeneratedEan] = React.useState(() => generateEan13("789"));
  const initialEan = initialData?.ean13 || initialData?.sku || autoGeneratedEan;

  const defaultValues: ProductFormData = {
    name: initialData?.name || "",
    ean13: initialEan,
    sku: initialEan,
    image_url: initialData?.image_url || null,
    category_id: initialData?.category_id || (categories[0]?.id ?? ""),
    cost_price: initialData?.cost_price || 0,
    sale_price: initialData?.sale_price || 0,
    description: initialData?.description || "",
    active: initialData?.active ?? true,
    variants: initialData?.variants?.map((v) => {
      const vEan = v.ean13 || v.barcode || v.sku_variant || generateEan13("789");
      return {
        id: v.id,
        size: v.size,
        color: v.color,
        ean13: vEan,
        sku_variant: vEan,
        barcode: vEan,
        active: v.active,
      };
    }) || [
      {
        size: "M",
        color: "Preto",
        ean13: generateEan13("789"),
        sku_variant: "",
        barcode: "",
        active: true,
      },
    ],
  };

  const {
    register,
    control,
    handleSubmit,
    watch,
    setValue,
    formState: { errors, isSubmitting },
  } = useForm<ProductFormData>({
    resolver: zodResolver(productFormSchema),
    defaultValues,
  });

  const { fields, append, remove, replace } = useFieldArray({
    control,
    name: "variants",
  });

  const currentEan = watch("ean13") || "";
  const currentImageUrl = watch("image_url");
  const costPrice = watch("cost_price") || 0;
  const salePrice = watch("sale_price") || 0;

  // Cálculo de Margem de Lucro Bruta Estimada
  const profitMargin =
    salePrice > 0 && costPrice >= 0
      ? (((salePrice - costPrice) / salePrice) * 100).toFixed(1)
      : null;

  // Iniciar fluxo da Câmera ao vivo
  const startCamera = async (facing: "environment" | "user" = cameraFacing) => {
    try {
      if (streamRef.current) {
        streamRef.current.getTracks().forEach((track) => track.stop());
      }
      setIsCameraOpen(true);
      const stream = await navigator.mediaDevices.getUserMedia({
        video: {
          facingMode: facing,
          width: { ideal: 1280 },
          height: { ideal: 1280 },
        },
      });
      streamRef.current = stream;
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
      }
    } catch {
      // Se não houver permissão ou der erro de stream, aciona a câmera nativa do sistema operacional
      setIsCameraOpen(false);
      if (nativeCameraInputRef.current) {
        nativeCameraInputRef.current.click();
      } else {
        toast.error("Câmera indisponível. Utilize o botão 'Escolher Arquivo'.");
      }
    }
  };

  // Parar Câmera
  const stopCamera = React.useCallback(() => {
    if (streamRef.current) {
      streamRef.current.getTracks().forEach((track) => track.stop());
      streamRef.current = null;
    }
    setIsCameraOpen(false);
  }, []);

  // Alternar entre câmera frontal e traseira
  const toggleCameraFacing = async () => {
    const nextFacing = cameraFacing === "environment" ? "user" : "environment";
    setCameraFacing(nextFacing);
    await startCamera(nextFacing);
  };

  // Capturar frame da câmera
  const capturePhoto = () => {
    if (!videoRef.current) return;
    const video = videoRef.current;
    const canvas = document.createElement("canvas");
    canvas.width = video.videoWidth || 800;
    canvas.height = video.videoHeight || 800;
    const ctx = canvas.getContext("2d");
    if (ctx) {
      ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
      const dataUrl = canvas.toDataURL("image/jpeg", 0.85);
      setValue("image_url", dataUrl, { shouldDirty: true });
      toast.success("Foto do produto capturada com sucesso!");
    }
    stopCamera();
  };

  // Processar upload de arquivo selecionado
  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    try {
      const compressed = await compressImageFile(file);
      setValue("image_url", compressed, { shouldDirty: true });
      toast.success("Foto carregada com sucesso!");
    } catch {
      toast.error("Erro ao carregar a foto do produto.");
    } finally {
      e.target.value = "";
    }
  };

  // Remover foto
  const handleRemovePhoto = () => {
    setValue("image_url", null, { shouldDirty: true });
    toast.info("Foto removida.");
  };

  // Cleanup da câmera ao desmontar
  React.useEffect(() => {
    return () => {
      if (streamRef.current) {
        streamRef.current.getTracks().forEach((track) => track.stop());
      }
    };
  }, []);

  // Alternar tamanho no gerador
  const toggleSize = (size: string) => {
    setSelectedSizes((prev) =>
      prev.includes(size) ? prev.filter((s) => s !== size) : [...prev, size]
    );
  };

  // Alternar cor no gerador
  const toggleColor = (color: string) => {
    setSelectedColors((prev) =>
      prev.includes(color) ? prev.filter((c) => c !== color) : [...prev, color]
    );
  };

  // Adicionar cor personalizada
  const addCustomColor = () => {
    const trimmed = customColor.trim();
    if (!trimmed) return;
    if (!selectedColors.includes(trimmed)) {
      setSelectedColors((prev) => [...prev, trimmed]);
    }
    setCustomColor("");
  };

  // Gerar novo código EAN-13 para o modelo base
  const handleGenerateNewEan = () => {
    const newEan = generateEan13("789");
    setValue("ean13", newEan, { shouldValidate: true, shouldDirty: true });
    setValue("sku", newEan);
    toast.info(`Novo código EAN-13 gerado: ${newEan}`);
  };

  // Gerar novo código EAN-13 para uma variação específica da tabela
  const handleRegenerateVariantEan = (index: number) => {
    const newEan = generateEan13("789");
    setValue(`variants.${index}.ean13`, newEan, { shouldValidate: true, shouldDirty: true });
    setValue(`variants.${index}.sku_variant`, newEan);
    setValue(`variants.${index}.barcode`, newEan);
    toast.info(`EAN-13 atualizado na variação: ${newEan}`);
  };

  // Gerar combinações de Grade automaticamente (cada peça ganha seu próprio EAN-13)
  const generateVariantsMatrix = () => {
    if (selectedSizes.length === 0 || selectedColors.length === 0) {
      toast.warning("Selecione pelo menos um tamanho e uma cor para gerar a grade.");
      return;
    }

    const newVariants: ProductVariantFormData[] = [];

    selectedSizes.forEach((size) => {
      selectedColors.forEach((color) => {
        const variantEan = generateEan13("789");
        newVariants.push({
          size,
          color,
          ean13: variantEan,
          sku_variant: variantEan,
          barcode: variantEan,
          active: true,
        });
      });
    });

    replace(newVariants);
    toast.success(`${newVariants.length} variações geradas com códigos EAN-13 exclusivos!`);
  };

  const onSubmit = async (data: ProductFormData) => {
    try {
      const ean = data.ean13 || generateEan13("789");
      const submissionData: ProductFormData = {
        ...data,
        ean13: ean,
        sku: ean,
        image_url: data.image_url || null,
        variants: data.variants.map((v) => {
          const vEan = v.ean13 || generateEan13("789");
          return {
            ...v,
            ean13: vEan,
            sku_variant: vEan,
            barcode: vEan,
          };
        }),
      };

      if (isEditing && initialData?.id) {
        const res = await productService.updateProduct(initialData.id, submissionData);
        if (res.error) {
          toast.error(res.error);
          return;
        }
        toast.success("Produto e variações atualizados com sucesso!");
      } else {
        const res = await productService.createProduct(submissionData);
        if (res.error) {
          toast.error(res.error);
          return;
        }
        toast.success("Produto cadastrado com sucesso!");
      }

      router.push("/products");
      router.refresh();
    } catch {
      toast.error("Ocorreu um erro ao salvar o produto.");
    }
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-8 animate-in fade-in duration-300">
      {/* Inputs ocultos de seleção de foto */}
      <input
        type="file"
        ref={fileInputRef}
        accept="image/*"
        className="hidden"
        onChange={handleFileChange}
      />
      <input
        type="file"
        ref={nativeCameraInputRef}
        accept="image/*"
        capture="environment"
        className="hidden"
        onChange={handleFileChange}
      />

      {/* Modal / Overlay da Câmera ao Vivo */}
      {isCameraOpen && (
        <div className="fixed inset-0 z-50 bg-black/85 backdrop-blur-xs flex flex-col items-center justify-center p-4">
          <div className="bg-background rounded-2xl max-w-md w-full overflow-hidden shadow-2xl border border-border flex flex-col">
            <div className="flex items-center justify-between p-4 border-b">
              <div className="flex items-center gap-2">
                <Camera className="w-5 h-5 text-[#E06B67]" />
                <h3 className="font-semibold text-sm">Tirar Foto do Produto</h3>
              </div>
              <Button
                type="button"
                variant="ghost"
                size="icon"
                className="h-8 w-8 rounded-full"
                onClick={stopCamera}
              >
                <X className="w-4 h-4" />
              </Button>
            </div>

            <div className="relative aspect-square bg-black overflow-hidden flex items-center justify-center">
              <video
                ref={videoRef}
                autoPlay
                playsInline
                className="w-full h-full object-cover"
              />
              {/* Mira visual para enquadramento da peça */}
              <div className="absolute inset-8 border border-white/40 rounded-xl pointer-events-none border-dashed" />
              <div className="absolute bottom-3 left-3 bg-black/60 backdrop-blur-md px-2.5 py-1 rounded-full text-[11px] text-white font-medium flex items-center gap-1.5">
                <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                Câmera Ativa
              </div>
            </div>

            <div className="p-4 bg-muted/30 flex items-center justify-between gap-3 border-t">
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={toggleCameraFacing}
                className="gap-1.5 text-xs"
                title="Inverter Câmera (Frontal / Traseira)"
              >
                <RotateCcw className="w-3.5 h-3.5" />
                Inverter
              </Button>

              <Button
                type="button"
                onClick={capturePhoto}
                className="bg-gradient-to-r from-[#E06B67] to-[#F48884] hover:opacity-90 text-white font-semibold gap-2 shadow-md px-5"
              >
                <Camera className="w-4 h-4" />
                Capturar Foto
              </Button>

              <Button
                type="button"
                variant="ghost"
                size="sm"
                onClick={stopCamera}
                className="text-xs"
              >
                Cancelar
              </Button>
            </div>
          </div>
        </div>
      )}

      {/* Barra Superior de Ações */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b">
        <div className="flex items-center gap-3">
          <Button asChild variant="outline" size="icon" className="h-9 w-9">
            <Link href="/products" aria-label="Voltar para a lista">
              <ArrowLeft className="h-4 w-4" />
            </Link>
          </Button>
          <div>
            <h1 className="text-2xl font-bold tracking-tight">
              {isEditing ? `Editar: ${initialData?.name}` : "Novo Produto"}
            </h1>
            <p className="text-xs text-muted-foreground">
              {isEditing
                ? "Atualize as informações da peça, foto e códigos EAN-13."
                : "Preencha os dados da peça, adicione foto e gere os códigos EAN-13."}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Button asChild variant="ghost">
            <Link href="/products">Cancelar</Link>
          </Button>
          <Button type="submit" disabled={isSubmitting} className="gap-2 bg-gradient-to-r from-[#E06B67] to-[#F48884] hover:opacity-95 text-white">
            <Save className="h-4 w-4" />
            {isSubmitting ? "Salvando..." : isEditing ? "Salvar Alterações" : "Salvar Produto"}
          </Button>
        </div>
      </div>

      <div className="grid gap-6 md:grid-cols-3">
        {/* Coluna 1 & 2: Foto, Dados Básicos e Precificação */}
        <div className="md:col-span-2 space-y-6">
          {/* Card: Foto da Peça */}
          <Card className="shadow-sm border">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <ImageIcon className="h-4 w-4 text-[#E06B67]" />
                  <CardTitle className="text-base">Foto do Produto</CardTitle>
                </div>
                <Badge variant="outline" className="text-[10px] text-muted-foreground">
                  Catálogo & PDV
                </Badge>
              </div>
              <CardDescription className="text-xs">
                Adicione a foto da peça ou tire na hora com a câmera para visualização rápida no caixa e estoque.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col sm:flex-row items-center gap-5">
                {/* Visualizador da Foto / Preview */}
                <div className="relative w-40 h-40 sm:w-44 sm:h-44 rounded-2xl border-2 border-dashed border-border/80 bg-muted/30 overflow-hidden flex flex-col items-center justify-center shrink-0 group shadow-xs">
                  {currentImageUrl ? (
                    <>
                      <img
                        src={currentImageUrl}
                        alt="Foto do Produto"
                        className="w-full h-full object-cover"
                      />
                      <button
                        type="button"
                        onClick={handleRemovePhoto}
                        className="absolute top-2 right-2 p-1.5 rounded-full bg-black/70 text-white hover:bg-rose-600 transition-colors shadow-md"
                        title="Remover foto"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </>
                  ) : (
                    <div className="flex flex-col items-center justify-center text-center p-3 text-muted-foreground">
                      <div className="h-12 w-12 rounded-xl bg-[#E06B67]/10 flex items-center justify-center text-[#E06B67] mb-2">
                        <Camera className="w-6 h-6" />
                      </div>
                      <span className="text-xs font-medium text-foreground">Sem Foto</span>
                      <span className="text-[10px] text-muted-foreground mt-0.5">Tire ou adicione</span>
                    </div>
                  )}
                </div>

                {/* Botões de Ação para Foto */}
                <div className="space-y-3 w-full">
                  <div className="flex flex-wrap gap-2.5">
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() => startCamera("environment")}
                      disabled={isSubmitting}
                      className="gap-2 text-xs border-[#E06B67]/30 hover:border-[#E06B67] hover:bg-[#E06B67]/5 text-foreground"
                    >
                      <Camera className="w-4 h-4 text-[#E06B67]" />
                      Tirar Foto com Câmera
                    </Button>

                    <Button
                      type="button"
                      variant="outline"
                      onClick={() => fileInputRef.current?.click()}
                      disabled={isSubmitting}
                      className="gap-2 text-xs"
                    >
                      <Upload className="w-4 h-4 text-muted-foreground" />
                      Escolher do Computador / Celular
                    </Button>

                    {currentImageUrl && (
                      <Button
                        type="button"
                        variant="ghost"
                        onClick={handleRemovePhoto}
                        disabled={isSubmitting}
                        className="gap-1.5 text-xs text-rose-600 hover:text-rose-700 hover:bg-rose-50"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                        Remover Foto
                      </Button>
                    )}
                  </div>

                  <p className="text-[11px] text-muted-foreground leading-relaxed">
                    Formatos aceitos: JPG, PNG, WEBP. A foto é otimizada automaticamente para não pesar no sistema e aparecer instantaneamente no PDV.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Card: Informações Gerais */}
          <Card className="shadow-sm border">
            <CardHeader>
              <div className="flex items-center gap-2">
                <Shirt className="h-4 w-4 text-[#E06B67]" />
                <CardTitle className="text-base">Informações do Modelo</CardTitle>
              </div>
              <CardDescription>
                Identificação principal da peça de vestuário e código de barras oficial.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="sm:col-span-2 space-y-2">
                  <Label htmlFor="name">Nome da Peça *</Label>
                  <Input
                    id="name"
                    placeholder="Ex: Vestido Midi Floral Evasê"
                    disabled={isSubmitting}
                    {...register("name")}
                  />
                  {errors.name && (
                    <p className="text-xs text-destructive">{errors.name.message}</p>
                  )}
                </div>

                {/* Código EAN-13 (substituindo SKU) */}
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <Label htmlFor="ean13" className="flex items-center gap-1.5 font-medium">
                      <Barcode className="w-3.5 h-3.5 text-[#E06B67]" />
                      Código EAN-13 *
                    </Label>
                    <Badge
                      variant="secondary"
                      className="text-[10px] px-1.5 py-0 bg-pink-50 text-pink-700 border-pink-200 flex items-center gap-1 font-normal"
                    >
                      <Sparkles className="w-2.5 h-2.5 text-pink-600" />
                      13 Dígitos
                    </Badge>
                  </div>
                  <div className="relative flex items-center">
                    <Input
                      id="ean13"
                      maxLength={13}
                      placeholder="Ex: 7891234567890"
                      className="font-mono font-semibold text-foreground pr-24 tracking-wider"
                      disabled={isSubmitting}
                      {...register("ean13")}
                    />
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      onClick={handleGenerateNewEan}
                      disabled={isSubmitting}
                      className="absolute right-1 top-1/2 -translate-y-1/2 h-7 text-xs text-[#E06B67] hover:text-[#E06B67] hover:bg-pink-50 px-2 gap-1 rounded font-medium transition-colors"
                      title="Gerar novo código EAN-13 automático com dígito verificador"
                    >
                      <RefreshCw className="w-3 h-3" />
                      Gerar EAN
                    </Button>
                  </div>
                  <div className="flex items-center justify-between text-[11px] text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <Check className="w-3 h-3 text-emerald-600" />
                      Código oficial de 13 dígitos
                    </span>
                    {currentEan && isValidEan13(currentEan) && (
                      <span className="text-[10px] text-emerald-600 font-medium flex items-center gap-1">
                        <CheckCircle2 className="w-3 h-3" />
                        Válido
                      </span>
                    )}
                  </div>
                  {errors.ean13 && (
                    <p className="text-xs text-destructive">{errors.ean13.message}</p>
                  )}
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="category_id">Categoria</Label>
                  <select
                    id="category_id"
                    disabled={isSubmitting}
                    className="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                    {...register("category_id")}
                  >
                    <option value="" className="bg-background text-foreground">
                      Selecione uma categoria
                    </option>
                    {categories.map((c) => (
                      <option key={c.id} value={c.id} className="bg-background text-foreground">
                        {c.name}
                      </option>
                    ))}
                  </select>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="active">Status</Label>
                  <select
                    id="active"
                    disabled={isSubmitting}
                    className="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                    value={watch("active") ? "true" : "false"}
                    onChange={(e) => setValue("active", e.target.value === "true")}
                  >
                    <option value="true" className="bg-background text-foreground">
                      Ativo (Disponível para venda no PDV)
                    </option>
                    <option value="false" className="bg-background text-foreground">
                      Inativo (Oculto)
                    </option>
                  </select>
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="description">Descrição / Composição do Tecido</Label>
                <textarea
                  id="description"
                  rows={3}
                  placeholder="Ex: 100% Viscose. Tecido leve, caimento fluido, forro interno e botões frontais."
                  disabled={isSubmitting}
                  className="flex w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                  {...register("description")}
                />
              </div>
            </CardContent>
          </Card>

          {/* Card: Precificação & Margem */}
          <Card className="shadow-sm border">
            <CardHeader>
              <div className="flex items-center gap-2">
                <DollarSign className="h-4 w-4 text-[#E06B67]" />
                <CardTitle className="text-base">Preços & Margem Comercial</CardTitle>
              </div>
              <CardDescription>
                Valores de custo de aquisição e venda da peça.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 items-center">
                <div className="space-y-2">
                  <Label htmlFor="cost_price">Preço de Custo (R$)</Label>
                  <Input
                    id="cost_price"
                    type="number"
                    step="0.01"
                    min="0"
                    placeholder="0,00"
                    disabled={isSubmitting}
                    {...register("cost_price")}
                  />
                  {errors.cost_price && (
                    <p className="text-xs text-destructive">{errors.cost_price.message}</p>
                  )}
                </div>

                <div className="space-y-2">
                  <Label htmlFor="sale_price">Preço de Venda (R$) *</Label>
                  <Input
                    id="sale_price"
                    type="number"
                    step="0.01"
                    min="0.01"
                    placeholder="0,00"
                    disabled={isSubmitting}
                    {...register("sale_price")}
                  />
                  {errors.sale_price && (
                    <p className="text-xs text-destructive">{errors.sale_price.message}</p>
                  )}
                </div>

                {/* Exibição da Margem Estimada */}
                <div className="rounded-lg border bg-muted/40 p-3 flex flex-col justify-center">
                  <span className="text-xs text-muted-foreground flex items-center gap-1">
                    <Percent className="h-3 w-3" />
                    Margem Bruta Estimada
                  </span>
                  <span
                    className={`text-lg font-bold mt-0.5 ${
                      Number(profitMargin) > 40
                        ? "text-emerald-600 dark:text-emerald-400"
                        : Number(profitMargin) > 20
                        ? "text-blue-600 dark:text-blue-400"
                        : "text-amber-600 dark:text-amber-400"
                    }`}
                  >
                    {profitMargin !== null ? `${profitMargin}%` : "-"}
                  </span>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Coluna 3: Gerador Rápido de Grade */}
        <div className="space-y-6">
          <Card className="shadow-sm border bg-muted/20">
            <CardHeader className="pb-3">
              <div className="flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-[#E06B67]" />
                <CardTitle className="text-sm font-semibold">
                  Gerador Rápido de Grade
                </CardTitle>
              </div>
              <CardDescription className="text-xs">
                Selecione tamanhos e cores para criar a matriz de peças com códigos EAN-13 automáticos.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Seleção de Tamanhos */}
              <div className="space-y-2">
                <Label className="text-xs font-semibold">Tamanhos Desejados</Label>
                <div className="flex flex-wrap gap-1.5">
                  {COMMON_CLOTHING_SIZES.map((size) => {
                    const isSelected = selectedSizes.includes(size);
                    return (
                      <button
                        type="button"
                        key={size}
                        onClick={() => toggleSize(size)}
                        className={`px-2.5 py-1 text-xs font-medium rounded-md border transition-all ${
                          isSelected
                            ? "bg-[#E06B67] text-white border-[#E06B67]"
                            : "bg-background text-foreground border-input hover:border-[#E06B67]/50"
                        }`}
                      >
                        {size}
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Seleção de Cores */}
              <div className="space-y-2">
                <Label className="text-xs font-semibold">Cores Desejadas</Label>
                <div className="flex flex-wrap gap-1.5 max-h-36 overflow-y-auto p-1 border rounded-md bg-background">
                  {COMMON_CLOTHING_COLORS.map((color) => {
                    const isSelected = selectedColors.includes(color);
                    return (
                      <button
                        type="button"
                        key={color}
                        onClick={() => toggleColor(color)}
                        className={`px-2 py-0.5 text-xs rounded border transition-all ${
                          isSelected
                            ? "bg-[#E06B67] text-white border-[#E06B67] font-medium"
                            : "bg-muted/50 text-muted-foreground border-transparent hover:border-input"
                        }`}
                      >
                        {color}
                      </button>
                    );
                  })}
                </div>

                {/* Adicionar Cor Extra */}
                <div className="flex gap-1.5 mt-2">
                  <Input
                    placeholder="Outra cor..."
                    value={customColor}
                    onChange={(e) => setCustomColor(e.target.value)}
                    className="h-8 text-xs"
                    onKeyDown={(e) => {
                      if (e.key === "Enter") {
                        e.preventDefault();
                        addCustomColor();
                      }
                    }}
                  />
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    className="h-8 text-xs px-2.5"
                    onClick={addCustomColor}
                  >
                    + Cor
                  </Button>
                </div>
              </div>

              <Button
                type="button"
                variant="secondary"
                className="w-full gap-2 text-xs h-9 mt-2 font-medium"
                onClick={generateVariantsMatrix}
              >
                <Sparkles className="h-3.5 w-3.5 text-[#E06B67]" />
                Gerar Matriz ({selectedSizes.length} × {selectedColors.length} ={" "}
                {selectedSizes.length * selectedColors.length} peças)
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Matriz de Variações de Grade com Código EAN-13 */}
      <Card className="shadow-sm border">
        <CardHeader className="flex flex-row items-center justify-between pb-3">
          <div>
            <div className="flex items-center gap-2">
              <Layers className="h-4 w-4 text-[#E06B67]" />
              <CardTitle className="text-base">Variações de Grade & Códigos EAN-13</CardTitle>
            </div>
            <CardDescription>
              Cada combinação de tamanho e cor possui um código de barras EAN-13 individual de 13 dígitos para bipar no caixa e controlar estoque.
            </CardDescription>
          </div>

          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={() => {
              append({
                size: "M",
                color: "Preto",
                ean13: generateEan13("789"),
                sku_variant: "",
                barcode: "",
                active: true,
              });
            }}
            className="gap-1.5 text-xs"
          >
            <Plus className="h-3.5 w-3.5 text-[#E06B67]" />
            Adicionar Variação Manual
          </Button>
        </CardHeader>
        <CardContent>
          {errors.variants && (
            <div className="mb-4 flex items-center gap-2 rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-xs text-destructive">
              <AlertCircle className="h-4 w-4 shrink-0" />
              <p>{errors.variants.message}</p>
            </div>
          )}

          <div className="overflow-x-auto border rounded-lg">
            <table className="w-full text-left text-xs">
              <thead className="bg-muted/50 border-b font-semibold text-muted-foreground">
                <tr>
                  <th className="px-3 py-2 w-28">Tamanho *</th>
                  <th className="px-3 py-2 w-44">Cor *</th>
                  <th className="px-3 py-2">Código EAN-13 da Peça (13 dígitos) *</th>
                  <th className="px-3 py-2 text-center w-24">Ativa</th>
                  <th className="px-3 py-2 text-right w-16">Remover</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {fields.length === 0 ? (
                  <tr>
                    <td colSpan={5} className="px-4 py-8 text-center text-muted-foreground">
                      Nenhuma variação adicionada. Use o gerador acima ou clique em &quot;Adicionar Variação Manual&quot;.
                    </td>
                  </tr>
                ) : (
                  fields.map((field, index) => (
                    <tr key={field.id} className="hover:bg-muted/20">
                      {/* Tamanho */}
                      <td className="p-2">
                        <Input
                          placeholder="Tam (P, M...)"
                          className="h-8 text-xs font-semibold"
                          disabled={isSubmitting}
                          {...register(`variants.${index}.size`)}
                        />
                      </td>

                      {/* Cor */}
                      <td className="p-2">
                        <Input
                          placeholder="Cor (Preto...)"
                          className="h-8 text-xs"
                          disabled={isSubmitting}
                          {...register(`variants.${index}.color`)}
                        />
                      </td>

                      {/* Código EAN-13 */}
                      <td className="p-2">
                        <div className="relative flex items-center">
                          <Input
                            placeholder="789..."
                            maxLength={13}
                            className="h-8 text-xs font-mono font-medium pr-16"
                            disabled={isSubmitting}
                            {...register(`variants.${index}.ean13`)}
                          />
                          <Button
                            type="button"
                            variant="ghost"
                            size="sm"
                            onClick={() => handleRegenerateVariantEan(index)}
                            disabled={isSubmitting}
                            className="absolute right-1 top-1/2 -translate-y-1/2 h-6 px-1.5 text-[10px] text-[#E06B67] hover:bg-pink-50"
                            title="Gerar novo código EAN-13 para esta variação"
                          >
                            <RefreshCw className="w-2.5 h-2.5 mr-1" />
                            Gerar
                          </Button>
                        </div>
                      </td>

                      {/* Ativa */}
                      <td className="p-2 text-center">
                        <input
                          type="checkbox"
                          className="h-4 w-4 rounded border-input text-primary focus:ring-primary cursor-pointer"
                          disabled={isSubmitting}
                          {...register(`variants.${index}.active`)}
                        />
                      </td>

                      {/* Botão Remover */}
                      <td className="p-2 text-right">
                        <Button
                          type="button"
                          variant="ghost"
                          size="icon"
                          onClick={() => remove(index)}
                          className="h-7 w-7 text-muted-foreground hover:text-destructive"
                          title="Remover variação"
                          disabled={fields.length === 1}
                        >
                          <Trash2 className="h-3.5 w-3.5" />
                        </Button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </CardContent>
        <CardFooter className="flex justify-between items-center border-t py-4 text-xs text-muted-foreground">
          <span>Total de variações: {fields.length}</span>
          <Button type="submit" disabled={isSubmitting} className="gap-2 bg-gradient-to-r from-[#E06B67] to-[#F48884] hover:opacity-95 text-white">
            <Save className="h-4 w-4" />
            {isSubmitting ? "Salvando..." : isEditing ? "Salvar Alterações" : "Salvar Produto"}
          </Button>
        </CardFooter>
      </Card>
    </form>
  );
}
